### ISSUE TITLE
Stop passing user IDs in URLs

### ISSUE THREAD

**Issue by bpatzke** [depaul-se-capstone-team-3/student-growth-tracker#108]
In controllers, we need to stop passing teacher and student ID values via URLs for use in queries. We should always use auth.user_id in queries. This is the easiest way to mitigate information leaks.

For example, you can type the id of any user in the URL for the student views to see that student's information.

**Comment by forevaufo** [comment]
Fixed it for student controller

**Comment by forevaufo** [comment]
I think this is ready to be close too.

**Comment by bpatzke** [comment]
The student portion of the classes menu needs to be fixed. It still passes the student_id to the controller.

**Comment by forevaufo** [comment]
Fixed
