### ISSUE TITLE
Student views are accessible to teachers.

### ISSUE THREAD

**Issue by bpatzke** [depaul-se-capstone-team-3/student-growth-tracker#114]
If you manually type in the correct URL, a teacher can see the student view for any student, regardless of that student's association with the teacher.

**Comment by forevaufo** [comment]
web2py ch 9

**Comment by bpatzke** [comment]
Example:

``@auth.requires(auth.user_id==1 or request.client=='127.0.0.1', requires_login=True)``

**Comment by forevaufo** [comment]
Using "student_id = auth.user_id" in students controller fixed this issue.

**Comment by forevaufo** [comment]
Issue ready to be close, please verify and close.

**Comment by bpatzke** [comment]
The application now crashes when a teacher loads the student screens.

We need to add a check for membership in the student role, and redirect on failure.

**Comment by forevaufo** [comment]
I tried adding constraint on @auth.requires, but it went straight to crashing the application.
How should this be done correctly ?
@auth.requires(auth.group_id == 2)  ?

**Comment by Larry-Graves** [comment]
before the function:
@auth.requires_login()

and after:

if auth.has_membership('Teacher'):
(whatever code you need)

should work.

**Comment by forevaufo** [comment]
Fixed for student controller.
Also found same bug on gradebook controller, fixed it too.

**Comment by bpatzke** [comment]
To check a role, you use this:

``auth.has_membership('Student')``
