### ISSUE TITLE
All actions in the standards controller are accessible to all users and do not require login.

### ISSUE THREAD

**Issue by bpatzke** [depaul-se-capstone-team-3/student-growth-tracker#122]

**Comment by forevaufo** [comment]
I dont think we have any use for this controller yet, but I added "@auth.requires_login()" to the two function it have.

**Comment by forevaufo** [comment]
Issue ready to be close, please verify and close.

**Comment by forevaufo** [comment]
I dont think we have any use for this controller yet, but I added "@auth.requires_login()" to the two function it have.
