### ISSUE TITLE
views/classes/overview.html repeated class name

### ISSUE THREAD

**Issue by Larry-Graves** [depaul-se-capstone-team-3/student-growth-tracker#125]
The overview for classes shows a non-link class name above the link class name.  The non-link should be removed.

**Comment by forevaufo** [comment]
Class/overview - Removed duplicate class name.
Class/overview - Formatted due soon's display date.

![image](https://cloud.githubusercontent.com/assets/8951691/11257727/39a92398-8e19-11e5-97fd-b94160a3536a.png)

**Comment by forevaufo** [comment]
Issue ready to be close, please verify and close.

**Comment by Larry-Graves** [comment]
Is that the format we're using?  We had discussed having the display format
be more like what the majority of U.S. programs seem to use, with
month/day/year.

**Comment by forevaufo** [comment]
That's using the DATE_FORMAT in db_01_general

**Comment by Larry-Graves** [comment]
Pretty sure we were going to create a DISPLAY_DATE_FORMAT as well, which
should be the different format.

If it doesn't exist yet, might make sense to create it.

**Comment by forevaufo** [comment]
![image](https://cloud.githubusercontent.com/assets/8951691/11280009/585c8d3e-8eb9-11e5-8ce1-98ca6c6c1eca.png)

**Comment by Larry-Graves** [comment]
Yep, that's much better.

**Comment by bpatzke** [comment]
If that's the format we're using, can you update issue #91 to reflect that?
