### ISSUE TITLE
Classes/Overview Due Soon behavior

### ISSUE THREAD

**Issue by Larry-Graves** [depaul-se-capstone-team-3/student-growth-tracker#128]
If there are no elements returned based on the due date query, we just end up with Due Soon and blank space underneath.  It seems like we should have a message instead that says "this class has no upcoming assignments" or something like that.

**Comment by forevaufo** [comment]
Yea i thought about this too, I will handle this.

**Comment by Larry-Graves** [comment]
Please also use icons to indicate the click-expand functionality for users.  Just something to indicate that it's a possibility.

**Comment by forevaufo** [comment]
Class/overview - Added message to indicate if there are nothing due.
![image](https://cloud.githubusercontent.com/assets/8951691/11257347/9bdef2ac-8e16-11e5-8e9d-cbaac2654d46.png)

**Comment by forevaufo** [comment]
Class/Overview - Added message to indicate when nothing is due soon.

![image](https://cloud.githubusercontent.com/assets/8951691/11257774/8684ecd8-8e19-11e5-84e7-3504671ad956.png)

**Comment by Larry-Graves** [comment]
lol nice

**Comment by forevaufo** [comment]
Student/Overview - Fixed displaying behavior 
1. Clicking on class name will go to student/index
2. Click on "Closed Folder" icon will show "Opened Folder" and due soon list.

![image](https://cloud.githubusercontent.com/assets/8951691/11261823/0aff0114-8e3e-11e5-9400-3f39fff55ad3.png)


![image](https://cloud.githubusercontent.com/assets/8951691/11261846/35b7f668-8e3e-11e5-88c6-4c478b66f8b2.png)

**Comment by forevaufo** [comment]
Issue ready to be close, please verify and close.

**Comment by bpatzke** [comment]
Please move the icons on the student overview screen to the left side of the text.

Also, change the color when you hover over the icon from black to a darker shade of the color we're using for the icon.

**Comment by forevaufo** [comment]
Fixed 
![image](https://cloud.githubusercontent.com/assets/8951691/11292412/2d971d94-8f13-11e5-9c66-e7207c3926f3.png)
