### ISSUE TITLE
Classes/Index table colors are not consistent

### ISSUE THREAD

**Issue by Larry-Graves** [depaul-se-capstone-team-3/student-growth-tracker#175]
The color scheme we're using in the Classes/Index view isn't the same as what we use elsewhere in the overview screens.  It's leading to some confusing experiences while moving through the screens.

The problem appears to be that test values aren't coloring properly.  I'm not sure why the colors would process incorrectly for the test values while working for the assignments.

**Comment by Larry-Graves** [comment]
Bryan, can you verify that this doesn't have anything to do with the display changes?  The renderer is an exceedingly simple construct, and I don't have quite enough time to figure out where the error is coming from if it's related to the table.

**Comment by bpatzke** [comment]
You mean the changes to the header?

**Comment by Larry-Graves** [comment]
the cell colors themselves

**Comment by bpatzke** [comment]
On my local copy, the cells color correctly for both tests and assignments. Therefore, the error was introduced at some point after pull request #161.

**Comment by bpatzke** [comment]
Larry, do you have time to check this?

**Comment by Larry-Graves** [comment]
It's working for me now.  I have no explanation for this.  

Yesterday, all test values were yellow no matter what.  

Closing issue.
