### ISSUE TITLE
Parents/Overview, Students/Overview, Classes/Overview - Coloring Logic

### ISSUE THREAD

**Issue by Larry-Graves** [depaul-se-capstone-team-3/student-growth-tracker#176]
The various overview screens do not appear to be using the same logic for coloring grades.  Student overview shows 77.89% as red, while Parent overview shows 77.89% as yellow.  The behavior should be standardized, and I have not yet ruled out a bug.

Allan, you have been handling the colors in our overviews, so I think this will be fastest for you to handle.

**Comment by forevaufo** [comment]
Fixed. Minor fix, whoever did the parent view was passing in wrong score.
![image](https://cloud.githubusercontent.com/assets/8951691/13030006/c865a8d6-d261-11e5-910a-c2d09630575f.png)

**Comment by forevaufo** [comment]
Larry confirm and close

**Comment by Larry-Graves** [comment]
Allan, the standards in the bottom graph aren't sorting correctly on my end for Classes/Overview.  Goes Three Four Five One Two.

**Comment by Larry-Graves** [comment]
Issues resolved.  Closing issue.
