### ISSUE TITLE
Standard Dropdown for "Create an Grade" has no option for not attaching a standard

### ISSUE THREAD

**Issue by Joseph-Richard** [depaul-se-capstone-team-3/student-growth-tracker#182]
I looked into this, and it does not seem like it is going to be a simple fix. From what I could tell, we will need to have some sort of default standard or something that is in the database and is referenced when we want to have a grade that does not have an associated standard. That was the only thing i could think to do from researching it.

**Comment by Larry-Graves** [comment]
reach out to Bryan please

**Comment by bpatzke** [comment]
Looking into it now.

**Comment by bpatzke** [comment]
This was resolved with pull request #185.
