### ISSUE TITLE
"Trend Detection Settings" crashes when I click on it.

### ISSUE THREAD

**Issue by bpatzke** [depaul-se-capstone-team-3/student-growth-tracker#220]
The specific error is "list index out of range."

**Comment by forevaufo** [comment]
I am not seeing this issue on my side...
Could you reload web2py and see if this error goes away ?

**Comment by Larry-Graves** [comment]
Bryan, do you have Allan's new .csv files?

**Comment by bpatzke** [comment]
No. Were they added to the Google Docs zip files?

**Comment by Larry-Graves** [comment]
he might have emailed them

**Comment by bpatzke** [comment]
Found the email. Is this test data, or demo data?

**Comment by Larry-Graves** [comment]
demo

**Comment by Larry-Graves** [comment]
no tests exist, but it needs to be in both I guess

**Comment by bpatzke** [comment]
Someone please add the new csv files to the zip archives in Google Docs.
