### ISSUE TITLE
The graph at the bottom of the parents/index page needs a heading and a legend.

### ISSUE THREAD

**Issue by bpatzke** [depaul-se-capstone-team-3/student-growth-tracker#224]
There's no way to know what that graph is showing.

**Comment by bpatzke** [comment]
Actually, this should be added to all of the graphs that don't have it.

**Comment by Larry-Graves** [comment]
Allan is fixing them.

**Comment by forevaufo** [comment]
![image](https://cloud.githubusercontent.com/assets/8951691/13658704/262b3d46-e63f-11e5-8df8-33e8dd6b0fcf.png)

![image](https://cloud.githubusercontent.com/assets/8951691/13658709/3b31c804-e63f-11e5-9e55-dfbcecafda4c.png)

![image](https://cloud.githubusercontent.com/assets/8951691/13658717/4e20c456-e63f-11e5-9709-8c6bf2b18123.png)

**Comment by forevaufo** [comment]
Fixed #226
