### ISSUE TITLE
Classes/Overview out of alignment

### ISSUE THREAD

**Issue by allanzguan** [depaul-se-capstone-team-3/student-growth-tracker#234]
I dont know if this is  how it suppose to look like but I think the classes/overview is out of alignment.

![image](https://cloud.githubusercontent.com/assets/8951691/13725992/05678dda-e879-11e5-93ea-49be5c29233c.png)

**Comment by ghost** [comment]
It's not out of alignment. There's extra space under "Standards" for that list to expand downward.

I was torn about this layout, but in real world use it should look more balanced.

**Comment by allanzguan** [comment]
If that is the case... I think we should add more standards in to make it appear better for the presentation

**Comment by Larry-Graves** [comment]
I can add some additional standards for the presentation.
