### ISSUE TITLE
There are two "standards" controllers.

### ISSUE THREAD

**Issue by bpatzke** [depaul-se-capstone-team-3/student-growth-tracker#26]
I'm not sure which controller - standard.py or standards.py - we should use.

Please update the standards.py file with the correct code.

**Comment by forevaufo** [comment]
Fixed it
---------------------------
Noting what I did in case I did it wrong : 
1. Removed old "standards.py" and updated "standard.py"
2. Renamed "standard.py" to "standards.py"

( I dont know why I did all those deleting and renaming, took me a while but now I am more familiar with git now )

**Comment by bpatzke** [comment]
Practice makes perfect. :)

Plus, a detailed description of what you've done is *always* a good thing - even if you just copy and paste your commit message. It helps everyone have a more complete picture of what's going on.

I'll take a look as soon as I get a chance.

**Comment by bpatzke** [comment]
Everything looks good. Closing issue.
