### ISSUE TITLE
models/db_50_grade.py - Wrong table referenced in id.readable/writeable statement.

### ISSUE THREAD

**Issue by bpatzke** [depaul-se-capstone-team-3/student-growth-tracker#30]
The statement that sets the ``id`` field of the ``grade`` table to not read/writable is incorrect.

Current statement:

    db.classes.id.readable = db.classes.id.writable = False

Correct statement:

    db.grade.id.readable = db.grade.id.writable = False

**Comment by bpatzke** [comment]
I'll take care of this one, as I have other things to do in this file anyway.

**Comment by Joseph-Richard** [comment]
My bad, I think i copied it over and forgot to switch out the class
specific pieces.

**Comment by bpatzke** [comment]
This was fixed a while ago. Closing issue.
