### ISSUE TITLE
The link between ``contentarea`` and ``standard`` is backward.

### ISSUE THREAD

**Issue by bpatzke** [depaul-se-capstone-team-3/student-growth-tracker#32]
The one-to-many relation between ``contentarea`` and ``standard`` needs to be implemented the other way around. I.e. ``standard`` records should have a reference to a ``contentarea``.

**Comment by Larry-Graves** [comment]
Standard isn't mine, but contentarea is, so I'll make this change.

**Comment by forevaufo** [comment]
I added a reference to contentarea in the standard model

**Comment by forevaufo** [comment]
standard model renamed from db_10 to db_25 because contentarea needs to load before standard

**Comment by bpatzke** [comment]
This was fixed a while back. Closing issue.
