### ISSUE TITLE
student_classes throws KeyError (ID)

### ISSUE THREAD

**Issue by Larry-Graves** [depaul-se-capstone-team-3/student-growth-tracker#45]
I'm trying to set up the mapping tables, and student_classes is throwing errors when trying to add new records.  I haven't dug in yet, as this is Joe's content, but I will if necessary.

Joe, are you able to fix?

**Comment by Joseph-Richard** [comment]
Yes i will look at it now

**Comment by Joseph-Richard** [comment]
This mapping table was created by Bryan. It looks fine to me, so I am not sure why it is throwing an error. I'll keep looking to see if I can figure it out

**Comment by Joseph-Richard** [comment]
I figured out the issue here. my pull request hadn't been pushed through yet so this mapping table does not exist yet. I have updated my repository to the newest version of the code, and will re-add the code for this table and the create methods in the controllers

**Comment by Larry-Graves** [comment]
I've been seeing the table, which definitely exists, so I'm not sure if
that's the problem.  Usually seeing issues like that points to something
with validators or declarations.

Have you loaded my database files?

**Comment by Joseph-Richard** [comment]
I ran into some issues with my local copy, so I deleted everything and set it up again. I should have the latest version of everything, i just need to go in and make the changes that were in my previous pull request. Do your database files automatically load when i launch web2py's ide?

**Comment by Larry-Graves** [comment]
Not yet, no.  I'll work on that later.  For the moment, you'll need to
manually import each one after you purge your database.

**Comment by Joseph-Richard** [comment]
Ok, I can do the deleting of all my database files , but I am just not sure how to go about importing yours then

**Comment by Larry-Graves** [comment]
you'll do so from the appadmin screens.  Once you're looking at a specific
table, there's an import function, and you select the .csv file that
corresponds to that table.

You'll need to load them in order.

**Comment by Joseph-Richard** [comment]
I will work on accomplishing that now

**Comment by Joseph-Richard** [comment]
I am having trouble finding the appadmin screens. can you point me in the right direction?

**Comment by Larry-Graves** [comment]
student_growth_tracker/appadmin

**Comment by Joseph-Richard** [comment]
That worked. Thanks

**Comment by bpatzke** [comment]
Is this resolved? If so, please close the issue.

**Comment by Larry-Graves** [comment]
resolved.
