### ISSUE TITLE
Teachers listed multiple times on Gradebook screen

### ISSUE THREAD

**Issue by bpatzke** [depaul-se-capstone-team-3/student-growth-tracker#63]
On the Gradebook screen, the teacher is listed once for each class they have. There should be one teacher heading, with a list of classes underneath.

![gradebook-screen](https://cloud.githubusercontent.com/assets/9020395/10711229/92377e6c-7a3a-11e5-99d3-cf12e02fb049.png)

**Comment by Larry-Graves** [comment]
currently working on that.

**Comment by Larry-Graves** [comment]
Issue resolved.  Headers were pulling teacher.name values, and are no longer doing so.
