### ISSUE TITLE
Flash message after redirect from ``grades/create``.

### ISSUE THREAD

**Issue by bpatzke** [depaul-se-capstone-team-3/student-growth-tracker#71]
We need to add ``session.flash = T("Class does not exist.")`` to the ``create`` controller wherever we redirect the user.

**Comment by forevaufo** [comment]
Updated with session.flash

**Comment by bpatzke** [comment]
This is resolved.

As I was working on merging the update for this, I realized that, since we're still using the ``default`` controller, any flash messages set prior to redirecting to ``/default/index`` will get clobbered because the ``index`` function sets ``response.flash``.

This leads to the question of how we'll handle the default controller. I have an idea, but I'll open a new issue for that.
